#!/bin/bash

git clone --recurse-submodules https://github.com/bspaulding/.vim.git $HOME/.vim
sh $HOME/.vim/install

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
cp ./tmux/.tmux.conf $HOME/.tmux.conf
